const router = express.Router();
const jwt = require('jsonwebtoken');
const Post = require('../models/Post');
const User = require('../models/User');
const ModerationService = require('../services/moderationService');
const logger = require('../utils/logger');
const { apiLimiter } = require('../middleware/rateLimitMiddleware');
const { checkPermission, PERMISSIONS } = require('../middleware/rbacMiddleware');
=======
const express = require('express');
const router = express.Router();
const jwt = require('jsonwebtoken');
const Post = require('../models/Post');
const User = require('../models/User');
const ModerationService = require('../services/moderationService');
const logger = require('../utils/logger');
const { apiLimiter } = require('../middleware/rateLimitMiddleware');
const { checkPermission, PERMISSIONS } = require('../middleware/rbacMiddleware');
const { uploadPostMedia, handleUploadError, getUploadedFileUrl, processUploadedFile } = require('../middleware/upload');
